### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by aemyers** [qwertydog/Reddit-Wallpaper-Changer#3]
`ERROR: Reddit server error: The request was aborted: Could not create SSL/TLS secure channel.`

Looks like reddit updated their API. 

https://www.reddit.com/r/redditsecurity/comments/oeyuom/tls_protocol_and_ciphersuite_modernization/

Any chance for an update on this fork? I find it the only usable version since the parent's thread management seems completely broken.

Some pointers that might help:
[How to specify SSL protocol to use for WebClient class](https://stackoverflow.com/a/31171327/)
[Default SecurityProtocol in .NET 4.5](https://stackoverflow.com/a/36454717/)

My guess is something like:
`System.Net.ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;`

Should work maybe somewhere in the [CreateWebClient](https://github.com/qwertydog/Reddit-Wallpaper-Changer/blob/master/Reddit%20Wallpaper%20Changer/HelperMethods.cs#L130-L156) method perhaps?

Maybe it is time for me to figure out how to compile a c# app...

**Comment by qwertydog** [comment]
Hi this should be fixed in the latest version. You'll probably need to download and install manually (as ironically the auto-update check had the same problem)

**Comment by aemyers** [comment]
Worked like a charm. Thank you!

**Comment by begundal** [comment]
using the latest version still got error
`https://pastebin.com/uLVEgy8K`

**Comment by qwertydog** [comment]
Have you got minimum .NET framework v4.7 installed (you can check via instructions here: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#detect-net-framework-45-and-later-versions). 

Which version of windows are you using? If you're using Windows 7, you may need to enable TLS 1.2 ([Windows 7](https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392))

**Comment by begundal** [comment]
using win 7 sp1
.NET Framework 4.8
MicrosoftEasyFix51044 installed
problem persists
`https://pastebin.com/hfumKdm9`

**Comment by qwertydog** [comment]
Can you access reddit via a web browser? e.g. [link](http://www.reddit.com/r/wallpapers/search.json?q=1920x1080+nsfw%3Ayes+self%3Ano+((url%3A.png+OR+url%3A.jpg+OR+url%3A.jpeg)+OR+(url%3Aimgur.png+OR+url%3Aimgur.jpg+OR+url%3Aimgur.jpeg)+OR+(url%3Adeviantart))&restrict_sr=on&sort=comments&t=month)

Can you run a manual update check? (About -> Check For Updates)
